### ISSUE TITLE
Visualization and Mesh is not same

### ISSUE THREAD

**Issue by Talegqz** [Colmar-zlicheng/Color-NeuS#1]
Thanks for your excellent work!

I found some config bug and fixed it, then I ran it with my own data. I found that the visualization is very nice, but the mesh quality is not reasonable.

Could you please explain it or help me improve it?

Thanks for your help.

<img width="1004" alt="Snipaste_2023-08-24_11-33-33" src="https://github.com/Colmar-zlicheng/Color-NeuS/assets/16120181/1e0b08c2-ea35-4b52-8851-e1da304d1c73">
<img width="622" alt="Snipaste_2023-08-24_11-33-43" src="https://github.com/Colmar-zlicheng/Color-NeuS/assets/16120181/5ec10595-59ba-42d3-91d7-f683aac691ee">

**Comment by Colmar-zlicheng** [comment]
Hi, that is because the resolution for reconstruction, the default value is 512. You can set it higher when doing evaluation. I think you can set it to 1024 to extract a more refined mesh, while it will take more time for inference.
```shell
python evaluation.py -rr 1024 --(other args)
```

**Comment by Talegqz** [comment]
Thanks for your help！

**Comment by xsl316** [comment]
Thanks for your excellent work!
How to train your own dataset, including how to preprocess your own data！
Thanks for your help.

**Comment by Colmar-zlicheng** [comment]
You can use the command below to train the IHO-Video dataset, please refer to readme for details.
```
python train.py -g 0 --cfg config/Color_NeuS_iho.yml -obj ghost_bear --exp_id Color_NeuS_iho_ghost_bear
```

For data preprocessing, we use colmap to obtain camera poses and TrackAnything to obtain image masks.
