### ISSUE TITLE
Failed to extract meshes using pretrained model

### ISSUE THREAD

**Issue by VerseWei** [Colmar-zlicheng/Color-NeuS#2]
Hello,
Many thanks for this great work.
When I train the model and place the weights in the specified path, then execute 
Python evaluation.py - g 0- c configs/Color_ NeuS_ Bmvs.yml - obj bear - rr 1024-- reload exp/Color_ NeuS_ Bmvs_ Bear_ 2023_ 0920_ 0604_ 55/checkpoints/checkpoints_ 100001/train_ param.pth.tar
I obtained the file 000000_ Mess.ply, I found the following regrettable result when opening it. May I ask if there were any errors in my operation?
![image](https://github.com/Colmar-zlicheng/Color-NeuS/assets/102359772/659f868f-73c8-4ce8-a724-965fdd6a5222)

**Comment by Colmar-zlicheng** [comment]
Hi, the checkpoints file is NeuS_Trainer.pth.tar, not the train_ param.pth.tar one.

**Comment by VerseWei** [comment]
Thank your very much，i will try it soon.

---- Replied Message ----
| From | Colmar | ***@***.***> |
| Date | 09/20/2023 20:26 |
| To | Colmar-zlicheng/Color-NeuS ***@***.***> |
| Cc | VerseWei ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Colmar-zlicheng/Color-NeuS] Failed to extract meshes using pretrained model (Issue #2) |

Hi, the checkpoints file is NeuS_Trainer.pth.tar, not the train_ param.pth.tar one.

**Comment by Colmar-zlicheng** [comment]
In commit 8f564c4, `strict` is set to `True` in `init_weights` to avoid this problem.
